# -*- coding: utf-8 -*-
"""Tahir_PatchTST_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jR8BfG0lMrKJDWgBEhPRFjkvXT87BnrN

# Demo: Data preprocessing + PatchTST forecasting (SPb COVID-19)

This notebook is prepared for a **demo** requested by the supervisor: **data preprocessing + PatchTST with graphs**.

**Dataset:** `SPb.COVID-19.united.csv` (uploaded alongside this notebook).

### What I will produce
1. Cleaned daily time series (with missing-value handling).
2. Several graphs (raw, missing values, train/test split).
3. PatchTST training + forecasts plot.

## 0) Setup

I use **Nixtla NeuralForecast** which includes an implementation of **PatchTST**.
"""

# Install dependencies (Colab)
!pip -q install neuralforecast==1.7.4 pandas matplotlib numpy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from neuralforecast import NeuralForecast
from neuralforecast.models import PatchTST

plt.rcParams['figure.figsize'] = (12, 4)

"""## 1) Load data

The repository README explains that the most complete dataset is `SPb.COVID-19.united.csv` and contains many variables.

I load it and inspect columns.
"""

DATA_PATH = '/content/SPb.COVID-19.united.csv'
df = pd.read_csv(DATA_PATH)
print('Shape:', df.shape)
df.head()

from google.colab import drive
drive.mount('/content/drive')

df.columns

"""## 2) Choose target variable

I Pick **one** time series for the demo.

Common candidates:
- `CONFIRMED.sk`, `DEATHS.sk`, `ACTIVE.sk`
- `PCR_TESTS`
- vaccination / beds / hospital indicators

Below I default to `PCR_TESTS` because it tends to be informative and less cumulative than `CONFIRMED`.
If you want a different variable, change `TARGET_COL`.
"""

TIME_COL = 'TIME.sk'
TARGET_COL = 'PCR_TESTS'  # <-- change if needed

assert TIME_COL in df.columns, f'Missing {TIME_COL}'
assert TARGET_COL in df.columns, f'Missing {TARGET_COL}'

# Parse datetime
df[TIME_COL] = pd.to_datetime(df[TIME_COL], errors='coerce')
df = df.dropna(subset=[TIME_COL]).sort_values(TIME_COL)

df[[TIME_COL, TARGET_COL]].head()

"""## 3) Preprocessing: aggregate to daily series + missing values

Because `TIME.sk` includes time-of-day, I convert to **daily** frequency:
- group by date
- aggregate using `sum` for flow-like variables (e.g., tests per day)
- or `last` for cumulative variables (e.g., confirmed cases)

I will automatically choose an aggregation rule:
- If the variable looks cumulative, use `last`
- Otherwise use `sum`

Then I create a continuous daily index and fill missing values.
"""

y_raw = df[[TIME_COL, TARGET_COL]].copy()
y_raw['date'] = y_raw[TIME_COL].dt.floor('D')

# Heuristic: cumulative-like column names
cumulative_keywords = ['CONFIRMED', 'DEATHS', 'RECOVERED', 'ACTIVE', 'V1.CS', 'V2.CS', 'VR1.CS', 'VR2.CS']
is_cumulative = any(k in TARGET_COL for k in cumulative_keywords)

if is_cumulative:
    daily = y_raw.groupby('date', as_index=False)[TARGET_COL].last()
    agg_used = 'last'
else:
    daily = y_raw.groupby('date', as_index=False)[TARGET_COL].sum(min_count=1)
    agg_used = 'sum'

print('Aggregation used:', agg_used)
daily = daily.rename(columns={'date': 'ds', TARGET_COL: 'y'})

# Build continuous daily index
full_index = pd.date_range(daily['ds'].min(), daily['ds'].max(), freq='D')
daily = daily.set_index('ds').reindex(full_index).rename_axis('ds').reset_index()

# Missing values summary
print('Missing y:', daily['y'].isna().sum())
daily.head()

# Fill missing values
# - cumulative: forward fill
# - non-cumulative: interpolate then fill remaining with 0
if is_cumulative:
    daily['y'] = daily['y'].ffill()
else:
    daily['y'] = daily['y'].interpolate(limit_direction='both')
    daily['y'] = daily['y'].fillna(0)

# Optional smoothing for noisy series (uncomment if needed)
# daily['y_smooth'] = daily['y'].rolling(7, min_periods=1).mean()

daily.describe()

"""### Graph 1: Raw daily time series"""

plt.figure()
plt.plot(daily['ds'], daily['y'])
plt.title(f'Daily series: {TARGET_COL} (agg={agg_used})')
plt.xlabel('Date'); plt.ylabel('y')
plt.show()

"""### Graph 2: Missing values indicator (before fill)

If you want to show missingness explicitly in your demo, rerun the earlier cell and store the missing mask.
Below we show an easy proxy: points where interpolation/ffill might have been applied.

"""

# Recompute a missing mask quickly from the reindexed (pre-fill) version
y_raw = df[[TIME_COL, TARGET_COL]].copy()
y_raw['date'] = y_raw[TIME_COL].dt.floor('D')
if is_cumulative:
    pre = y_raw.groupby('date', as_index=False)[TARGET_COL].last().rename(columns={'date':'ds', TARGET_COL:'y'})
else:
    pre = y_raw.groupby('date', as_index=False)[TARGET_COL].sum(min_count=1).rename(columns={'date':'ds', TARGET_COL:'y'})
full_index = pd.date_range(pre['ds'].min(), pre['ds'].max(), freq='D')
pre = pre.set_index('ds').reindex(full_index).rename_axis('ds').reset_index()
missing_mask = pre['y'].isna().astype(int)

plt.figure()
plt.plot(pre['ds'], missing_mask)
plt.title('Missing values (1=missing, 0=present)')
plt.xlabel('Date'); plt.ylabel('Missing')
plt.ylim(-0.1, 1.1)
plt.show()

"""## 4) Prepare data for PatchTST (NeuralForecast format)

NeuralForecast expects a **long** dataframe:
- `unique_id`: series identifier
- `ds`: datetime
- `y`: target

"""

ts = daily.copy()
ts['unique_id'] = 'SPB_COVID'
ts = ts[['unique_id', 'ds', 'y']]
ts.head()

"""## 5) Train/test split

We keep the last **90 days** for testing (you can change this).
"""

TEST_DAYS = 90
ts = ts.sort_values('ds')
cutoff = ts['ds'].max() - pd.Timedelta(days=TEST_DAYS)

train = ts[ts['ds'] <= cutoff].copy()
test = ts[ts['ds'] > cutoff].copy()

print('Train:', train.shape, 'Test:', test.shape)

plt.figure()
plt.plot(train['ds'], train['y'], label='train')
plt.plot(test['ds'], test['y'], label='test')
plt.title('Train/Test split')
plt.xlabel('Date'); plt.ylabel('y')
plt.legend()
plt.show()

"""## 6) Train PatchTST

Key parameters:
- `h`: forecast horizon (e.g., 14 days)
- `input_size`: history length used as input (e.g., 60 days)

For a demo, we keep training fast.
"""

H = 14
INPUT_SIZE = 60

model = PatchTST(
    h=H,
    input_size=INPUT_SIZE,
    max_steps=500,           # increase if you want better accuracy
    learning_rate=1e-3,
    batch_size=32,
    scaler_type='standard',  # internal scaling
)

nf = NeuralForecast(models=[model], freq='D')
nf.fit(df=train)

"""## 7) Forecast and visualize"""

pred = nf.predict()
pred.head()

# Merge last part of history + predictions for plotting
history_window = ts[ts['ds'] >= (train['ds'].max() - pd.Timedelta(days=180))].copy()

plt.figure()
plt.plot(history_window['ds'], history_window['y'], label='history')

# pred has columns: unique_id, ds, PatchTST
plt.plot(pred['ds'], pred['PatchTST'], label='PatchTST forecast')

plt.axvline(train['ds'].max(), linestyle='--', label='train end')
plt.title(f'PatchTST Forecast (H={H}) for {TARGET_COL}')
plt.xlabel('Date'); plt.ylabel('y')
plt.legend()
plt.show()

"""## 8) Simple evaluation on test period (optional)

We can do a simple evaluation if the forecast horizon overlaps with test.
For a full backtesting evaluation, we can add NeuralForecast cross-validation later.
"""

# Compare forecast to actuals where dates overlap
test_merge = test.merge(pred[['ds','PatchTST']], on='ds', how='inner')
if len(test_merge) == 0:
    print('No overlap between forecast horizon and test set. Increase H or change TEST_DAYS.')
else:
    mae = np.mean(np.abs(test_merge['y'] - test_merge['PatchTST']))
    rmse = np.sqrt(np.mean((test_merge['y'] - test_merge['PatchTST'])**2))
    print('Overlap points:', len(test_merge))
    print('MAE:', mae)
    print('RMSE:', rmse)

    plt.figure()
    plt.plot(test_merge['ds'], test_merge['y'], label='actual')
    plt.plot(test_merge['ds'], test_merge['PatchTST'], label='forecast')
    plt.title('Forecast vs Actual (overlap)')
    plt.xlabel('Date'); plt.ylabel('y')
    plt.legend()
    plt.show()

# =========================
# 9) Comparison setup
# =========================
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
import torch
import torch.nn as nn

# Use the same approved train/test split from above
comparison_train = train.copy()
comparison_test = test.copy()

# Forecast horizon for fair comparison
COMPARISON_H = len(comparison_test)
LOOKBACK = 60

print("Comparison horizon:", COMPARISON_H)
print("Train rows:", len(comparison_train))
print("Test rows:", len(comparison_test))

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def smape(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return 100 * np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred) + 1e-8))

"""Cell 10 — Classical EWS indicators

This is the first class your professor asked for.
"""

# =========================
# 10) Classical EWS indicators
# =========================
ews_window = 30

ews_df = daily.copy()
ews_df['rolling_variance'] = ews_df['y'].rolling(ews_window).var()
ews_df['rolling_ar1'] = ews_df['y'].rolling(ews_window).apply(
    lambda x: pd.Series(x).autocorr(lag=1), raw=False
)

plt.figure(figsize=(12,4))
plt.plot(ews_df['ds'], ews_df['rolling_variance'], label='Rolling Variance')
plt.plot(ews_df['ds'], ews_df['rolling_ar1'], label='Rolling AR(1)')
plt.axvline(comparison_train['ds'].max(), linestyle='--', color='black', label='train end')
plt.title(f'Classical EWS Indicators ({TARGET_COL})')
plt.xlabel('Date')
plt.ylabel('Indicator value')
plt.legend()
plt.show()

ews_df[['ds', 'y', 'rolling_variance', 'rolling_ar1']].tail()

"""Cell 11 — AR(1) forecasting baseline

This gives you a simple classical statistical baseline.
"""

# =========================
# 11) AR(1) forecasting baseline
# =========================
train_y = comparison_train['y'].values.astype(float)
test_y = comparison_test['y'].values.astype(float)

# Estimate AR(1): y_t = c + phi * y_{t-1}
y_lag = train_y[:-1]
y_now = train_y[1:]

phi = np.cov(y_lag, y_now, bias=True)[0, 1] / (np.var(y_lag) + 1e-8)
c = np.mean(y_now) - phi * np.mean(y_lag)

print("Estimated AR(1):")
print("c =", c)
print("phi =", phi)

ar1_preds = []
prev = train_y[-1]

for _ in range(COMPARISON_H):
    pred_val = c + phi * prev
    ar1_preds.append(pred_val)
    prev = pred_val

ar1_preds = np.array(ar1_preds)

plt.figure(figsize=(12,4))
plt.plot(comparison_test['ds'], test_y, label='Actual')
plt.plot(comparison_test['ds'], ar1_preds, label='AR(1)')
plt.title('AR(1) Forecast vs Actual')
plt.xlabel('Date')
plt.ylabel('y')
plt.legend()
plt.show()

"""Cell 12 — Prepare sequence data for LSTM / Transformer / PR-Patch

This is shared by the next models.
"""

# =========================
# 12) Prepare sequence data
# =========================
full_series = ts[['ds', 'y']].copy()

scaler = MinMaxScaler()
full_series['y_scaled'] = scaler.fit_transform(full_series[['y']])

train_scaled = full_series[full_series['ds'] <= comparison_train['ds'].max()]['y_scaled'].values
test_scaled_full = full_series[full_series['ds'] > comparison_train['ds'].max()]['y_scaled'].values

# We need the last LOOKBACK points from train to build test windows
combined_test_input = np.concatenate([train_scaled[-LOOKBACK:], test_scaled_full])

def make_sequences(series, lookback):
    X, y = [], []
    for i in range(len(series) - lookback):
        X.append(series[i:i+lookback])
        y.append(series[i+lookback])
    X = np.array(X)
    y = np.array(y)
    return X, y

X_train, y_train = make_sequences(train_scaled, LOOKBACK)
X_test, y_test = make_sequences(combined_test_input, LOOKBACK)

X_train = X_train.reshape(-1, LOOKBACK, 1)
X_test = X_test.reshape(-1, LOOKBACK, 1)

print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train.reshape(-1, 1), dtype=torch.float32).to(device)
X_test_t = torch.tensor(X_test, dtype=torch.float32).to(device)

"""Cell 13 — Standard LSTM

This is the second class: standard deep learning without physical constraints.
"""

# =========================
# 13) Standard LSTM
# =========================
class LSTMModel(nn.Module):
    def __init__(self, input_size=1, hidden_size=64):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :])
        return out

lstm_model = LSTMModel().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=1e-3)

epochs = 50

for epoch in range(epochs):
    lstm_model.train()
    optimizer.zero_grad()
    pred = lstm_model(X_train_t)
    loss = criterion(pred, y_train_t)
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f"LSTM Epoch {epoch+1}/{epochs}, Loss: {loss.item():.6f}")

lstm_model.eval()
with torch.no_grad():
    lstm_preds_scaled = lstm_model(X_test_t).cpu().numpy()

lstm_preds = scaler.inverse_transform(lstm_preds_scaled).flatten()

plt.figure(figsize=(12,4))
plt.plot(comparison_test['ds'], test_y, label='Actual')
plt.plot(comparison_test['ds'], lstm_preds, label='LSTM')
plt.title('LSTM Forecast vs Actual')
plt.xlabel('Date')
plt.ylabel('y')
plt.legend()
plt.show()

"""**Cell 14 — Standard Transformer**

This is the other standard deep learning baseline.
"""

# =========================
# 14) Standard Transformer
# =========================
class TransformerModel(nn.Module):
    def __init__(self, input_dim=1, d_model=64, nhead=4, num_layers=2):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, d_model)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            batch_first=True
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc = nn.Linear(d_model, 1)

    def forward(self, x):
        x = self.input_proj(x)
        x = self.encoder(x)
        x = self.fc(x[:, -1, :])
        return x

transformer_model = TransformerModel().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(transformer_model.parameters(), lr=1e-3)

epochs = 50

for epoch in range(epochs):
    transformer_model.train()
    optimizer.zero_grad()
    pred = transformer_model(X_train_t)
    loss = criterion(pred, y_train_t)
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f"Transformer Epoch {epoch+1}/{epochs}, Loss: {loss.item():.6f}")

transformer_model.eval()
with torch.no_grad():
    transformer_preds_scaled = transformer_model(X_test_t).cpu().numpy()

transformer_preds = scaler.inverse_transform(transformer_preds_scaled).flatten()

plt.figure(figsize=(12,4))
plt.plot(comparison_test['ds'], test_y, label='Actual')
plt.plot(comparison_test['ds'], transformer_preds, label='Transformer')
plt.title('Transformer Forecast vs Actual')
plt.xlabel('Date')
plt.ylabel('y')
plt.legend()
plt.show()

"""**Cell 15 — PatchTST baseline for fair comparison**

Keep your original approved PatchTST section unchanged.
This new cell is only for the comparison table, because now we need PatchTST on the same full test horizon.
"""

# =========================
# 15) PatchTST baseline for fair comparison
# =========================
from neuralforecast import NeuralForecast
from neuralforecast.models import PatchTST

patch_model_cmp = PatchTST(
    h=COMPARISON_H,
    input_size=LOOKBACK,
    max_steps=500,
    learning_rate=1e-3,
    batch_size=32,
    scaler_type='standard'
)

nf_cmp = NeuralForecast(models=[patch_model_cmp], freq='D')
nf_cmp.fit(df=comparison_train)

patch_cmp_pred = nf_cmp.predict()
patch_cmp_pred.head()

"""**Cell 16 — PatchTST plotting**"""

patchtst_preds = patch_cmp_pred['PatchTST'].values

plt.figure(figsize=(12,4))
plt.plot(comparison_test['ds'], test_y, label='Actual')
plt.plot(comparison_test['ds'], patchtst_preds, label='PatchTST')
plt.title('PatchTST Forecast vs Actual')
plt.xlabel('Date')
plt.ylabel('y')
plt.legend()
plt.show()

"""Cell 17 — PR-Patch model

This is a practical thesis-friendly physics-regularized version.
It is not your old PatchTST cell, and it adds a regularization term.
"""

# =========================
# PR-Patch Model Definition
# =========================

class PRPatchModel(nn.Module):

    def __init__(
        self,
        input_dim=1,
        d_model=64,
        nhead=4,
        num_layers=2
    ):
        super().__init__()

        self.input_proj = nn.Linear(
            input_dim,
            d_model
        )

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            batch_first=True
        )

        self.encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.fc = nn.Linear(
            d_model,
            1
        )

    def forward(self, x):

        x = self.input_proj(x)

        x = self.encoder(x)

        x = self.fc(
            x[:, -1, :]
        )

        return x


# =========================
# SIR-based Physics Loss
# =========================

def sir_physics_loss(pred, beta=0.25, gamma=0.10):

    pred = pred.squeeze()

    dI = pred[1:] - pred[:-1]

    expected_growth = (beta - gamma) * pred[:-1]

    residual = dI - expected_growth

    return torch.mean(residual ** 2)


# =========================
# PR-Patch Training
# =========================

pr_model = PRPatchModel().to(device)

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    pr_model.parameters(),
    lr=1e-3
)

lambda_phys = 0.05

epochs = 50

for epoch in range(epochs):

    pr_model.train()

    optimizer.zero_grad()

    pred = pr_model(X_train_t)

    data_loss = criterion(pred, y_train_t)

    phys_loss = sir_physics_loss(
        pred,
        beta=0.25,
        gamma=0.10
    )

    loss = data_loss + lambda_phys * phys_loss

    loss.backward()

    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(
            f"PR-Patch Epoch {epoch+1}/{epochs}, "
            f"Data Loss: {data_loss.item():.6f}, "
            f"Physics Loss: {phys_loss.item():.6f}"
        )


# =========================
# Predictions
# =========================

pr_model.eval()

with torch.no_grad():

    pr_preds_scaled = pr_model(X_test_t).cpu().numpy()

pr_preds = scaler.inverse_transform(
    pr_preds_scaled
).flatten()


# =========================
# Forecast Plot
# =========================

plt.figure(figsize=(12,4))

plt.plot(
    comparison_test['ds'],
    test_y,
    label='Actual'
)

plt.plot(
    comparison_test['ds'],
    pr_preds,
    label='PR-Patch'
)

plt.title('PR-Patch Forecast vs Actual')

plt.xlabel('Date')

plt.ylabel('Cases')

plt.legend()

plt.show()

# =========================
# Physics Consistency Error - Physical Consistency Error (PCE)
# =========================

beta = 0.25
gamma = 0.10

physics_residual = (
    pr_preds[1:]
    - pr_preds[:-1]
) - (
    (beta - gamma)
    * pr_preds[:-1]
)

plt.figure(figsize=(12,4))

plt.plot(physics_residual)

plt.title("Physics Consistency Error (PCE)")

plt.xlabel("Time")

plt.ylabel("Residual")

plt.grid(True)

plt.show()

print(
    "Mean Physics Error:",
    np.mean(np.abs(physics_residual))
)

"""**Cell** 19 — Final comparison table
**bold text**
"""

# =========================
# 18) Final comparison table
# =========================
results = []

def add_result(name, y_true, y_pred):
    results.append({
        'Model': name,
        'MAE': mean_absolute_error(y_true, y_pred),
        'RMSE': rmse(y_true, y_pred),
        'sMAPE': smape(y_true, y_pred)
    })

add_result('AR(1)', test_y, ar1_preds)
add_result('LSTM', test_y, lstm_preds)
add_result('Transformer', test_y, transformer_preds)
add_result('PatchTST', test_y, patchtst_preds)
add_result('PR-Patch', test_y, pr_preds)

results_df = pd.DataFrame(results).sort_values('RMSE').reset_index(drop=True)
results_df

"""**Cell 20 — Final all-model plot**"""

# =========================
# 19) All models vs actual
# =========================
plt.figure(figsize=(14,5))
plt.plot(comparison_test['ds'], test_y, label='Actual', linewidth=2)
plt.plot(comparison_test['ds'], ar1_preds, label='AR(1)')
plt.plot(comparison_test['ds'], lstm_preds, label='LSTM')
plt.plot(comparison_test['ds'], transformer_preds, label='Transformer')
plt.plot(comparison_test['ds'], patchtst_preds, label='PatchTST')
plt.plot(comparison_test['ds'], pr_preds, label='PR-Patch')

plt.title(f'Model Comparison for {TARGET_COL}')
plt.xlabel('Date')
plt.ylabel('y')
plt.legend()
plt.show()

"""Lambda Sensitivity Study

"""

# =========================
# Lambda Sensitivity Study
# =========================

lambda_values = [0.01, 0.05, 0.10, 0.20]

lambda_results = []

# =========================
# Train PR-Patch for One Lambda
# =========================

def train_pr_patch(lambda_phys):

    model = PRPatchModel().to(device)

    criterion = nn.MSELoss()

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=1e-3
    )

    epochs = 50

    for epoch in range(epochs):

        model.train()

        optimizer.zero_grad()

        pred = model(X_train_t)

        data_loss = criterion(
            pred,
            y_train_t
        )

        phys_loss = sir_physics_loss(
            pred,
            beta=0.25,
            gamma=0.10
        )

        loss = (
            data_loss
            + lambda_phys * phys_loss
        )

        loss.backward()

        optimizer.step()

    model.eval()

    with torch.no_grad():

        preds_scaled = model(
            X_test_t
        ).cpu().numpy()

    preds = scaler.inverse_transform(
        preds_scaled
    ).flatten()

    mae = mean_absolute_error(
        test_y,
        preds
    )

    rmse = np.sqrt(
        mean_squared_error(
            test_y,
            preds
        )
    )

    smape = (
        np.mean(
            2*np.abs(preds-test_y)
            /
            (
                np.abs(preds)
                +
                np.abs(test_y)
            )
        )
        *100
    )

    return mae, rmse, smape

# =========================
# Run Lambda Study
# =========================

for lam in lambda_values:

    mae, rmse, smape = train_pr_patch(lam)

    lambda_results.append(
        [lam, mae, rmse, smape]
    )

    print(
        f"Lambda={lam} | "
        f"MAE={mae:.2f} | "
        f"RMSE={rmse:.2f} | "
        f"sMAPE={smape:.2f}"
    )

"""Lambda result"""

lambdas = [0.01, 0.05, 0.10, 0.20]

rmse_values = [
    15845.15,
    5852.04,
    7046.25,
    12086.76
]

plt.figure(figsize=(8,4))

plt.plot(
    lambdas,
    rmse_values,
    marker='o'
)

plt.title(
    'Lambda Sensitivity Analysis'
)

plt.xlabel(
    'Physics Regularization Weight (λ)'
)

plt.ylabel(
    'RMSE'
)

plt.grid(True)

plt.show()

"""
# Physics-Law Violation Comparison
"""

# =========================
# PatchTST Physics Violations
# =========================

beta = 0.25
gamma = 0.10

patch_physics_residual = (
    patchtst_preds[1:]
    - patchtst_preds[:-1]
) - (
    (beta - gamma)
    * patchtst_preds[:-1]
)

patch_pce = np.mean(
    np.abs(patch_physics_residual)
)

print(
    "PatchTST Physics Error:",
    patch_pce
)

physics_residual

pr_pce = np.mean(
    np.abs(physics_residual)
)

print(
    "PR-Patch Physics Error:",
    pr_pce
)

physics_comparison = pd.DataFrame({

    "Model": [
        "PatchTST",
        "PR-Patch"
    ],

    "Physics_Error": [
        patch_pce,
        pr_pce
    ]

})

physics_comparison

plt.figure(figsize=(7,4))

plt.bar(
    physics_comparison["Model"],
    physics_comparison["Physics_Error"]
)

plt.title(
    "Physics-Law Violation Comparison"
)

plt.ylabel(
    "Mean Physics Consistency Error"
)

plt.grid(
    axis='y'
)

plt.show()

"""The above proposed SIR-inspired regularization did not reduce the Physics Consistency Error on the PCR_TESTS dataset. This suggests that simple SIR dynamics may not fully capture the complex temporal behavior of testing activity."""